services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    C4Y\Block4you\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php,Resources/contao}'
